---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellokube
  name: hellokube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
