---
apiVersion: v1
kind: Pod
metadata:
  name: hellokube
spec:
  containers:
    - name: hello-app
      image: gcr.io/google-samples/hello-app:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          name: http
