---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellokube
  name: hellokube
  namespace: demo
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.hello-app: glob:release*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
      - name: hello-app
        image: docker-repo.vpc.locusdev.net/stephenapp:1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
